# Generated by Django 4.0.3 on 2022-03-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
