# Generated by Django 4.0.3 on 2022-03-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num',
            new_name='qty',
        ),
    ]
