# Generated by Django 4.0.3 on 2022-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_remove_product_qty_product_qty_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='qty',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
