# Generated by Django 4.0.3 on 2022-03-24 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orderproduct_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
