# Generated by Django 4.0.3 on 2022-03-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orderproduct_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='date',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='api.order'),
        ),
    ]
