version: '2'

services:
  inventory:
    build: ./inventory
    command: bash -c "python3 ./inventory/manage.py makemigrations && python3 ./inventory/manage.py migrate && python3 ./inventory/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always

  reporting:
    build: ./reporting
    command: bash -c "python3 ./reporting/manage.py makemigrations && python3 ./reporting/manage.py migrate && python3 ./reporting/manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/code
    ports:
      - 8002:8002
    restart: always
    